# Generated by Django 5.1.2 on 2024-11-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_discription_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
