# Generated by Django 5.1.2 on 2024-11-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
