# Generated by Django 5.1.2 on 2024-11-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
